builders:
  localizationBuilder:
    import: 'package:localization_generator/localization_code_gen.dart'
    builder_factories: ['localizationBuilder']
    build_extensions:
      .json:
        - .dart
    build_to: source
    auto_apply: dependents